<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>fraudrules</string>
   </array>
  <key>name</key>
  <string>fraudrules</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.fraudrules</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.fraudrules</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([-\x{002b}\/\x{002a}\x{003d}\x{003c}\x{003e}\x{0021}\?\x{003a}\x{0021}]+)</string>
          <key>name</key>
          <string>keyword.operator.fraudrules</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(func)(\s+)([a-z\x{0024}][\w\x{0024}]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.fraudrules</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.fraudrules</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.fraudrules</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9]+)(\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.fraudrules</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.fraudrules</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:rule|case|returns|if| or |and|by|default|switch)\b</string>
          <key>name</key>
          <string>keyword.fraudrules</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false|null|undefined)</string>
          <key>name</key>
          <string>keyword.other.unit.fraudrules</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-z\x{0024}][\w\x{0024}]*)</string>
          <key>name</key>
          <string>variable.parameter.fraudrules</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.fraudrules</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.fraudrules</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.fraudrules</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.fraudrules</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.fraudrules</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>none.fraudrules</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.fraudrules</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.fraudrules</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.fraudrules</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0x[a-f\d]+|[-\x{002b}]?(?:\.\d+|\d+\.?\d*)(?:e[-\x{002b}]?\d+)?)</string>
          <key>name</key>
          <string>constant.numeric.fraudrules</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
